### ISSUE TITLE
ElastAlert not compiling because exotel pins to requests==2.2.1

### ISSUE THREAD

**Issue by fabianlee** [sarathsp06/exotel-py#3]
When installing ElastAlert (python setup.py install), the following error is thrown and the installation is halted because exotel requires the module 'requests==2.2.1' while ElastAlert's requirements.txt uses 2.5.1

_error: requests 2.5.1 is installed but requests==2.2.1 is required by set(['exotel'])_

This error does not occur until you run ElastAlert's 'pip install -r requirements.txt', but after you do that, this issue will occur every time you try to run install.

Can exotel be modified to work with >=2.2.1 ?

**Comment by sarathsp06** [comment]
Currently exotel requirement is `requests==2.13.0`. You may update `ElastAlert` requirements.txt

**Comment by fabianlee** [comment]
I tested moving ElastAlert's requirements up to exotel==0.1.3, requests==2.13.0, requests-oauthlib==0.5.0, and pip started throwing traceback errors at the very end of 'pip install -r requirements.txt' similar to the message in the thread below which is pointing to an issue with using that version of 'requests'

https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991

Does exotel really have a hard technical requirement on this version? or is this just a preference to keep it using the latest version of the module?

https://github.com/Yelp/elastalert/issues/1023

**Comment by sarathsp06** [comment]
> Does exotel really have a hard technical requirement on this version? or is this just a preference to keep it using the latest version of the module?


The version upgrade was to address: http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

Now I have updated the requirements file to have `requests>=2.5.1` as the requirement.
